Add aws lib to fix s3a write
Apparently, writing to S3 was broken with non-backwards compatible
changes to the api. Including an older version of the JAR fixes my write
errors. Without this jar I get a NoSuchMethodError error from AWS.
Reference article:
http://deploymentzone.com/2015/12/20/s3a-on-spark-on-aws-ec2/